

apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx1
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80 
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx2
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80 
