apiVersion: apps/v1
kind: Deployment
metadata:
  name: esttcr-deployment
spec:
  selector:
    matchLabels:
      app: esttcr
  replicas: 2 
  template:
    metadata:
      labels:
        app: esttcr
    spec:
      containers:
      - name: esttcr container
        image: nginx:1.14.2
        ports:
        - containerPort: 80