apiVersion: v1
kind: ReplicaSet
metadata:
  name: esteticar-rpc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      name: esteticar-ui-rpc
      labels:
        app: myapp
    spec:
      containers:
        - name: esteticar-ui-container
          image: nginx
          ports:
            - containerPort: 80
